#!/usr/bin/env ruby

require "csv"

def ts_string(value)
  value.to_s.inspect
end

rows = CSV.read("docs/outofloop-missions-v1.csv", headers: true)
out = []

out << "export type MissionMode = \"coragem\" | \"social\" | \"familia\" | \"saude\" | \"recomeco\";"
out << "export type MissionIntensity = \"leve\" | \"real\" | \"coragem\";"
out << "export type CostTier = \"gratis\" | \"low_cost\" | \"medio\" | \"especial\";"
out << "export type DurationLabel = \"micro\" | \"leve\" | \"realista\" | \"plano\" | \"maior\";"
out << ""
out << "export type Mission = {"
out << "  slug: string;"
out << "  title: string;"
out << "  description: string;"
out << "  mode: MissionMode;"
out << "  intensity: MissionIntensity;"
out << "  costTier: CostTier;"
out << "  estimatedMinutes: number;"
out << "  durationLabel: DurationLabel;"
out << "  recommendedTimeBlocks: string[];"
out << "  soloEnabled: boolean;"
out << "  pairEnabled: boolean;"
out << "  groupEnabled: boolean;"
out << "  familyEnabled: boolean;"
out << "  accessibilityNote: string;"
out << "  accessibleAlternativeTitle: string;"
out << "  accessibleAlternativeDescription: string;"
out << "};"
out << ""
out << "export const missions: Mission[] = ["

rows.each do |row|
  blocks = row["recommended_time_blocks"].to_s.split(",").map(&:strip).reject(&:empty?)
  out << "  {"
  out << "    slug: #{ts_string(row["slug"])},"
  out << "    title: #{ts_string(row["title"])},"
  out << "    description: #{ts_string(row["title"])},"
  out << "    mode: #{ts_string(row["mode"])},"
  out << "    intensity: #{ts_string(row["intensity"])},"
  out << "    costTier: #{ts_string(row["cost_tier"])},"
  out << "    estimatedMinutes: #{row["estimated_minutes"].to_i},"
  out << "    durationLabel: #{ts_string(row["duration_label"])},"
  out << "    recommendedTimeBlocks: [#{blocks.map { |block| ts_string(block) }.join(", ")}],"
  out << "    soloEnabled: #{row["solo_enabled"]},"
  out << "    pairEnabled: #{row["pair_enabled"]},"
  out << "    groupEnabled: #{row["group_enabled"]},"
  out << "    familyEnabled: #{row["family_enabled"]},"
  out << "    accessibilityNote: #{ts_string(row["accessibility_notes"])},"
  out << "    accessibleAlternativeTitle: #{ts_string(row["accessible_alternative_title"])},"
  out << "    accessibleAlternativeDescription: #{ts_string(row["accessible_alternative_description"])}"
  out << "  },"
end

out << "];"
out << ""
out << "export type MissionPreferences = {"
out << "  primaryMode?: MissionMode;"
out << "  secondaryMode?: MissionMode;"
out << "  preferredIntensity?: MissionIntensity;"
out << "  preferredCostTier?: CostTier;"
out << "  privateFirst?: boolean;"
out << "  hasChildren?: boolean;"
out << "  maxMinutes?: number;"
out << "};"
out << ""
out << "export function selectMissionOfTheDay(preferences: MissionPreferences = {}, date = new Date()): Mission {"
out << "  const daySeed = Number(`${date.getFullYear()}${date.getMonth() + 1}${date.getDate()}`);"
out << "  const candidates = missions"
out << "    .filter((mission) => !preferences.primaryMode || mission.mode === preferences.primaryMode || mission.mode === preferences.secondaryMode)"
out << "    .filter((mission) => !preferences.privateFirst || mission.soloEnabled)"
out << "    .filter((mission) => !preferences.maxMinutes || mission.estimatedMinutes <= preferences.maxMinutes);"
out << ""
out << "  const pool = candidates.length > 0 ? candidates : missions;"
out << "  const scored = pool.map((mission, index) => {"
out << "    let score = 0;"
out << "    if (mission.mode === preferences.primaryMode) score += 60;"
out << "    if (mission.mode === preferences.secondaryMode) score += 30;"
out << "    if (mission.intensity === preferences.preferredIntensity) score += 20;"
out << "    if (mission.costTier === preferences.preferredCostTier) score += 20;"
out << "    if (mission.costTier === \"gratis\") score += 8;"
out << "    if (preferences.hasChildren && mission.familyEnabled) score += 20;"
out << "    if (preferences.privateFirst && mission.soloEnabled) score += 12;"
out << "    score += ((daySeed + index * 17) % 29);"
out << "    return { mission, score };"
out << "  });"
out << ""
out << "  scored.sort((a, b) => b.score - a.score);"
out << "  return scored[0].mission;"
out << "}"

File.write("outofloop-app/src/data/missions.generated.ts", out.join("\n"))
puts "Generated outofloop-app/src/data/missions.generated.ts with #{rows.length} missions"
